server:
  port: 8090
  error:
    whitelabel:
      enabled: true

swagger:
  host:
    url: http://localhost:8090

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs.html
    operationsSorter: method

spring:
  application:
    name: test-app
  datasource:
    url: jdbc:mysql://127.0.0.1:7908/testdb?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    password: 123456
    username: root
    hikari:
      maxLifetime: 140000
  liquibase:
    url: jdbc:mysql://127.0.0.1:7908/testdb?createDatabaseIfNotExist=true
    user: root
    password: 123456
    change-log: classpath*:/db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true